name: tracing-app-example-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  RUST_LOG: debug
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tracing-app-example

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  push:
    needs: [test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tracing-app-example

    # https://docs.github.com/en/free-pro-team@latest/actions/guides/publishing-docker-images
    # https://github.com/docker/build-push-action
    steps:
    - name: Checkout baseline
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up docker buildx
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        #    - name: Build and Push to Docker Hub
        #      id: docker_build
        #      uses: docker/build-push-action@v2
        #      with:
        #        context: ./tracing-app-example
        #        file: ./tracing-app-example/Dockerfile
        #        push: true
        #        tags: unboundev/tracing-app:latest
        #    - name: Image digest
        #      run echo ${{ steps.docker_build.outputs.digest }}
