name: tracing-app-example

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  RUST_LOG: debug
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tracing-app-example

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  push:
    needs: [test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tracing-app-example

    steps:
    - uses: actions/checkout@v2
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: unboundev/tracing-app
        tag_with_ref: true